### ISSUE TITLE
SIMPLEOPENNI FOR ARM ON RASPBERRY PI

### ISSUE THREAD

**Issue by azizeh1380** [totovr/Processing#1]
hi I want to use simpleopenni library for processing 3 in raspberry pi. but can not find this library compatible for raspberry pi. may help me which way can find it? thanks | hi I want to use simpleopenni library for processing 3 in raspberry pi. but can not find this library compatible for raspberry pi. may help me which way can find it? thanks

**Comment by totovr** [comment]
Hello! unfortunately this version that I'm supporting just work for OSX users and also Windows users (just with 2.2.1 version of Processing), if you want to use Kinect V1 or V2 in Raspberry you can use OpenKinect version developed by Shiffman [Link](http://shiffman.net/p5/kinect/), but he doesn't provide support for Skeleton Tracking

**Comment by azizeh1380** [comment]
hi
thanks for your attention.but I want to have skeleton tracking.do you know which way can compile your's simppleopenni for ARM architecture?
best wishes

**Comment by totovr** [comment]
@azizeh1380 As I said below SimpleOpenni has not support for ARM architecture, just OpenKinect has support for this one (I already tried Kinect V2 in Raspberry Pi3 and OpenKinect), so is not possible to do Skeleton Tracking with SimpleOpenni and Raspberry
